#!/usr/bin/env python
# -*- coding: utf-8 -*-

from TaxiFareModel.trainer import Trainer
from TaxiFareModel.data import get_data, clean_data
from sklearn.model_selection import train_test_split


N = 10_000
df = get_data(nrows=N)
# clean data
df = clean_data(df)
# Delete 1.January 2009
df = df[df['key'].str.contains("2009-01-01") == False]
# set X and y
y = df["fare_amount"]
X = df.drop("fare_amount", axis=1)
# hold out
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=42, test_size=0.3)
# train
trainer = Trainer(X_train, y_train)
trainer.run()
# evaluate
res = trainer.evaluate(X_test, y_test)
#save_model
trainer.save_model()

print(res)
